### ISSUE TITLE
Report on full dependency tree

### ISSUE THREAD

**Issue by lahdekorpi** [OSSIndex/auditjs#13]
I can't understand how the tool would even be that useful without this...
Trusting that the maintainers of your dependencies keep up to date is a bad idea.

**Comment by OSSIndex-Admin** [comment]
Yup, I completely agree. I need to improve the documentation and command line help, because it is possible to get an audit for the full dependency list -- so long as you have *installed* the packages using `npm install`. You do this by changing to your application directory and running `auditjs` without any arguments. It should find all of the package dependencies and perform a full audit.

I just tested this by running `auditjs` in a random directory and only getting the vulnerabilities for my `node` application reported, but when I cd into the auditjs directory and run the command the tool processes 455 dependencies.

It is more difficult for us to run a fully transitive dependency scan at the moment when run against a standalone packages.config file, since we would have to either:

1. Maintain a full database of package dependencies, which can change every release
2. Download and audit all packages

We have considered doing both of these options at various times, but there has not been much call for this (so long as you can run against all dependencies once they are installed).

I am leaving this issue report open until I get a chance to update the documentation and command line help, which I shall attempt to do in the next few days.

**Comment by OSSIndex-Admin** [comment]
As a side issue, while testing to ensure it works properly I did note that packages are audited multiple times (quite likely if their inclusion is via multiple transitive include paths). I have opened a new issue to track this problem:

https://github.com/OSSIndex/auditjs/issues/14

**Comment by OSSIndex-Admin** [comment]
Hmm. And I wonder if it might be better if we run in a different way:

* If the `packages.config` file has a `node_modules` sibling then perform a full transitive dependency scan
* If the `packages.config` file does not have the `node_modules` sibling then simply run against the listed packages
* Provide a new option to restrict the command to direct dependencies only (in case someone was interested in only direct dependencies for whatever reason)

This would be a more expected manner of operating, I should think.

**Comment by qacwnfq** [comment]
It seems one can get the dependency tree of a package without installing it:
https://github.com/npm/npm-remote-ls

I'm not sure about the versioning though.
Flattening this tree and checking against it in the case of a package.json might be a solution.

**Comment by lahdekorpi** [comment]
Just tested this again and yes, it seems to work just fine when the packages have been installed.
Having to have the packages installed is a fair requirement in my opinion, and it is something that other similar tools also require.

So yeah, a documentation thing.

In cases where packages have been installed through `yarn`, you could use the `yarn.lock` file for the package version information.

**Comment by OSSIndex-Admin** [comment]
Good idea! I have opened a new issue (https://github.com/OSSIndex/auditjs/issues/16) to track yarn support.

**Comment by OSSIndex-Admin** [comment]
Sorry for taking so long in getting back to things. It has been a crazy busy couple of months, but I am getting back to updating all of the client tools.

Just a quick question. Does the information in the yarn.lock file differ from that in the packages.json file that it generates, or have you otherwise noticed problems with yarn support in the current auditjs? I just ran some tests (at long last) and things seem to work fine, but my knowledge of yarn is very, very limited.

**Comment by OSSIndex-Admin** [comment]
The README has been updated to make it more clear that transitive dependencies are audited if they are installed in the project under audit.
