### ISSUE TITLE
Usage Instructions for auditjs

### ISSUE THREAD

**Issue by svavantsa** [OSSIndex/auditjs#19]
I don't know what I am missing. I installed nodejs for Windows, then installed auditjs with npm install auditjs -g command. Then I rebooted the PC and then I run auditjs -v and it says "auditjs is not recognized as a in internal or external command, operable program or batch file". What am I missing?

I am using Windows 7.

**Comment by OSSIndex-Admin** [comment]
I am using Windows 8.1 which *should* be close enough.

I just tried uninstalling then installing my auditjs, and have the exact same results as you do. I am reasonably sure I know the reason and am planning on having a new version published tonight which will hopefully resolve the issue. I will be introducing a new command name `auditjs-win` which will be intended to target windows.

The issue seems to be a fix that was put in to handle some aggravating issues with some Linux distributions, which apparently have broken Windows installation.

Sorry about that. I will write again as soon as we have a fix published.

**Comment by svavantsa** [comment]
Thank you. For your honesty and hardwork.

**Comment by OSSIndex-Admin** [comment]
Alright, I have added an `auditjs-win` binary/shortcut which should allow things to work on windows again. I will keep looking for a better cross-platform solution for these problems, but at least there is now a workaround.

Thank you for the issue!
