### ISSUE TITLE
Auditjs exits with errno 4

### ISSUE THREAD

**Issue by eriktoyra** [OSSIndex/auditjs#22]
When running `npm run auditjs` on my project *auditjs* exits with `errno 4` after having completed an audit of all of the installed packages. `errno 4` indicates a "resource not available" error, but I can't figure out why this is happening. Nothing in the *auditjs* logs indicates that there are an unavailable resource. The audit log is working fine otherwise.

*Node:* v8.7.2
*NPM:* 5.4.2
*auditjs:* 2.2.2

```
npm ERR! code ELIFECYCLE
npm ERR! errno 4
npm ERR! xxx-xxx-xxx@1.0.0 auditjs: `auditjs`
npm ERR! Exit status 4
npm ERR!
npm ERR! Failed at the xxx-xxx-xxx@1.0.0 auditjs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxxxxx/.npm/_logs/2017-10-18T07_33_26_556Z-debug.log
```

**Comment by OSSIndex-Admin** [comment]
Hmm. Quite odd. I will try and reproduce the problem later on today and let you know my results. Would you be able to send your package.json file, by any chance?

**Comment by OSSIndex-Admin** [comment]
I have not been able to reproduce the problem yet on Linux or my Mac. A copy of your package.json file would be useful. Barring that, the line showing the full arguments for auditjs you are using would possibly be helpful, and some (all) of the dependencies perhaps (in case it is something odd with a specific dependency).

Is there any extra useful information in the `/Users/xxxxxxx/.npm/_logs/2017-10-18T07_33_26_556Z-debug.log` file?

**Comment by eriktoyra** [comment]
Thank's for looking into it! I have created a [gist for my package.json](https://gist.github.com/eriktoyra/d42f5f9fc324fe36209f74863b7cbc27). I run _auditjs_ as `npm run auditjs`.

This is how the .npm log looks like:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.7.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'auditjs' ]
2 info using npm@5.4.2
3 info using node@v8.7.0
4 verbose run-script [ 'preauditjs', 'auditjs', 'postauditjs' ]
5 info lifecycle xxxxx-xxx-xx@1.0.0~preauditjs: xxxxx-xxx-xx@1.0.0
6 info lifecycle xxxxx-xxx-xx@1.0.0~auditjs: xxxxx-xxx-xx@1.0.0
7 verbose lifecycle xxxxx-xxx-xxi@1.0.0~auditjs: unsafe-perm in lifecycle true
8 verbose lifecycle xxxxx-xxx-xx@1.0.0~auditjs: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/xxxx.xxxxx/Projects/xxxxx-xxx-xx/node_modules/.bin:/Users/xxxx.xxxxx/.rvm/gems/ruby-2.0.0-p481/bin:/Users/xxxx.xxxxx/.rvm/gems/ruby-2.0.0-p481@global/bin:/Users/xxxx.xxxxx/.rvm/rubies/ruby-2.0.0-p481/bin:/usr/local/sbin:/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/bin:/usr/local/opt/icu4c/sbin:/usr/local/opt/icu4c/bin:/Users/xxxx.xxxxx/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/Scripts/Xxxxxxxx:/Users/xxxx.xxxxx/.rvm/bin
9 verbose lifecycle xxxxx-xxx-xx@1.0.0~auditjs: CWD: /Users/xxxx.xxxxx/Projects/xxxxx-xxx-xx
10 silly lifecycle xxxxx-xxx-xx@1.0.0~auditjs: Args: [ '-c', 'auditjs' ]
11 silly lifecycle xxxxx-xxx-xx@1.0.0~auditjs: Returned: code: 4  signal: null
12 info lifecycle xxxxx-xxx-xxi@1.0.0~auditjs: Failed to exec auditjs script
13 verbose stack Error: xxxxx-xxx-xx@1.0.0 auditjs: `auditjs`
13 verbose stack Exit status 4
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid xxxxx-xxx-xx@1.0.0
15 verbose cwd /Users/xxxxx.xxxx/Projects/xxxxx-xxxx/xxxxx-xxx-xx
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/Cellar/node/8.7.0/bin/node" "/usr/local/bin/npm" "run" "auditjs"
18 verbose node v8.7.0
19 verbose npm  v5.4.2
20 error code ELIFECYCLE
21 error errno 4
22 error xxxxx-xxx-xx@1.0.0 auditjs: `auditjs`
22 error Exit status 4
23 error Failed at the xxxxx-xxx-xx@1.0.0 auditjs script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 4, true ]
```

**Comment by ken-duck** [comment]
Wow. I totally allowed myself to get distracted and missed the obvious answer :| . I noticed that there were errors on the server side that roughly corresponded with my test, but it turns out that those errors were not related to my tests (they were coincidentally only related by time of occurrence).

Anyhow, the tool is working as expected! The return code of `4` does not mean `resource not available`, but is the number of vulnerabilities found to be impacting your packages.

Sorry that this did not occur to me earlier. Its been staring me straight in the face the whole time but for whatever reason I was blind.

However, perhaps for your use case you do not want an error number returned. If you run with the `-r` or `--report` flag a JUnit report will be written into a `reports` directory and the return code should always be zero. Will this be sufficient? If not I can add a new option to make the return code 0 when desired.

Sorry again for the delay.

**Comment by eriktoyra** [comment]
> Anyhow, the tool is working as expected! The return code of 4 does not mean resource not available, but is the number of vulnerabilities found to be impacting your packages.

Thank you for looking into this. I think that returning the number of vulnerabilities found is incorrect because that implies that something broke the process in `auditjs` itself. `auditjs` never broke, it did its job perfectly so it should exit with `0`. Returning something other than `0` may possibly break CI builds and that's not what we want with `auditjs`. 

### Desired behavior
- Return with exit code 0 regardless of how many vulnerabilities were found.
- As a log message, output how many vulnerabilities were found at the end of the `auditjs` run
- ... or output the path to where the log reports were written so that it's possible to inspect them further.

**Comment by OSSIndex-Admin** [comment]
For now I have added a new option to suppress the error code on exit. I cannot make the default due to other people likely depending on the default. The new option is

```
--suppressExitError
```

I suspect I will have to clean up the options at some point in the future, and will do that on a major version change (probably providing a wrapper that preserves the original options). Till then I hope this will suffice.

----

I have additionally added a summary at the bottom (info logger).

If you request a report (-r) it does mention the relative path to the XML report.

I hope these changes handle the problem. Please let me know if they are insufficient. Sorry for the wait, and thanks for your help and feedback!
