### ISSUE TITLE
Using AuditJS with a proxy

### ISSUE THREAD

**Issue by Michael-Davies** [OSSIndex/auditjs#26]
Great stuff! I'm behind a corporate firewall, is it possible for me to use this with a proxy?

**Comment by OSSIndex-Admin** [comment]
Soon! There is a pull request in the works that should allow this to work. I will let you know as soon as it is available.

**Comment by OSSIndex-Admin** [comment]
Hi. Sorry for the delay, but I have finally merged the PR giving us this feature. The new version is `2.3.0`.  It uses the `request` package for rest calls, which provides proxy support which is documented here: https://www.npmjs.com/package/request#proxies

Please let me know if this works for you. I do not have an easy way to test this set up at the moment.

**Comment by cheesestringer** [comment]
Trying to use the proxy but it relies on environment variables rather than the npmrc config.

**Comment by ken-duck** [comment]
Yup. I'm looking at the npmrc information now. It should not be too hard to make it use those settings appropriately.

**Comment by ken-duck** [comment]
At long last I have added support for the npmrc file as well. Sorry it took so long.

As before, I do not have a good way of testing this currently, so if you notice anything please do let me know.

At the same time I have upgraded auditjs to use the new OSS Index v3 API, which has numerous benefits, primarily:

* More vulnerabilities
* The database is being actively maintained (v2 database is no longer maintained)

There is some rate limiting on the v3 API. For many use cases this will not be noticed, in particular because this new version does some result caching as well. If you run into a situation where you are failing due to the rate limit, you can create an account at OSS Index for free to up the rate limit. This should help us prevent abuse. It is not intended to get in the way of regular use, so if you notice a problem please do let us know.

I will be adding more information to the README about accounts and how to configure OSS Index to use the account (can be done command line, but we have also added config file support).
