### ISSUE TITLE
--quiet flag throws TypeError

### ISSUE THREAD

**Issue by tcschiller** [OSSIndex/auditjs#43]
```
$ auditjs-win --quiet
TypeError: Cannot read property 'level' of undefined
    at exports.Logger.logger.isLevelEnabled (C:\myProject\node_modules\auditjs\audit.js:163:42)
```
That's pretty much it. Looks like verbose mode properly adds an `EventEmitter` with a `level` property to `this.transports` but quiet mode doesn't.

**Comment by ken-duck** [comment]
This has been fix (as per PR merge above).

Just an FYI, a new version (3.0.3) has been uploaded. It provides several key features (among other things):

* Support for OSS Index API v3
** More vulnerabilities
** The v3 database is actively maintained, the v2 DB is no longer maintained
* Authentication support, as the v3 API rate limits, but a free account raises the rate limit. Depending on your usage you may not require an account, otherwise it is free (just intended to help reduce abuse)
* Configuration files, for when your command line options are getting onerous. Particularly useful for the authentication information.

I will be updating the README shortly on these new features.
