### ISSUE TITLE
Do not bundle with npm

### ISSUE THREAD

**Issue by DanielRuf** [OSSIndex/auditjs#53]
npm is a dependency of auditjs and currently contains a vulnerability which is found by snyk.

```
✗ Medium severity vulnerability found in cryptiles
  Description: Insecure Randomness
  Info: https://snyk.io/vuln/npm:cryptiles:20180710
  Introduced through: libcipm@2.0.1
  From: libcipm@2.0.1 > npm-lifecycle@2.0.3 > node-gyp@3.7.0 > request@2.81.0 > hawk@3.1.3 > cryptiles@2.0.5
  Remediation:
    Your dependencies are out of date, otherwise you would be using a newer version of cryptiles. 
    Try deleting node_modules, reinstalling and running `snyk test` again. If the problem persists, one of your dependencies may be bundling outdated modules.
```

Generally there should not be another npm.
In general, users should have the option to choose the used package manager (like others do with flags like `--yarn`, `--bower`, `--npm` and so on).

**Comment by DanielRuf** [comment]
Mh, seems so far it is not so easy to solve this as we need an alternative solution for the resolution of the dependencies.

**Comment by ken-duck** [comment]
Thanks for the report! This was (I think) fixed a few days ago: https://github.com/OSSIndex/auditjs/commit/d53ed4289ef745d193b514d1725f0490d89737c6

It is fixed in the new 3.0.x release version (https://www.npmjs.com/package/auditjs).

It was also discovered using the new 3.0.x release version. This upgrade allows auditjs to use the newest version of OSS Index which has MANY more vulnerabilities in its database (and it being actively maintained). I strongly recommend upgrading.

I will be making another 2.x release with a note to upgrade to 3.x, at the same time I will look into fixing the dependency there as well to keep things clear.

**Comment by ken-duck** [comment]
Looks like you are using the 3.x stream. I will look deeper into the issue you found and see if I can resolve it. Thanks again for the heads up!

**Comment by DanielRuf** [comment]
For reference:

```
auditjs --version
3.0.6
```

**Comment by ken-duck** [comment]
So you know, our security researchers have dug into the details and it seems that npm does not appear to be vulnerable to the cryptiles issue. We will be sure to upgrade to any newer version of npm if they update the cryptiles dependency so the false positive disappears.

Thank you for drawing our attention to the issue (and your other reports as well). It is very appreciated.
