### ISSUE TITLE
question about pkg:npm in cache

### ISSUE THREAD

**Issue by DanielRuf** [OSSIndex/auditjs#60]
It seems there is now a change. Is this expected? (I guess yes as it looks correct now but it i a bit confusing that both URLs work).

https://github.com/DanielRuf/auditjs-cache/commit/bdc63095c476b6a10e42b1e3126e4eb9f9eabd2a

**Comment by ken-duck** [comment]
It is expected. The original audit.js was using an older form of [PURLs](https://github.com/package-url/purl-spec) which did not have the "pkg:" prefix. We have since upgraded to use the more modern PURLs with the prefix, and have updated the cache data along with it.

Old cache files should be cleaned up automatically, all going well.

**Comment by ken-duck** [comment]
I believe the contents remained the same. Note that auditjs tries to overwrite the files when it runs, as there may be new vulnerabilities found for a package and those new vulnerabilities would be added to the cache.

The cached files are currently "valid" for 24 hours (I think) at which time auditjs will hit the server for new data.
