### ISSUE TITLE
Why node_modules and not package-lock.json?

### ISSUE THREAD

**Issue by joh-klein** [OSSIndex/auditjs#72]
It has probably been answered before, but I can't find that answer: why do you traverse the node_modules folder and not use the contents of package-lock.json (yarn.lock)?

**Comment by ken-duck** [comment]
Actually, that is a good question.

When I wrote audit.js, the package-lock.json file didn't exist. Audit.js was first released on October 6th, 2015, while the package-lock.json file apparently didn't exist until May 25th, 2017.

Funny thing is, I do not maintain a lot of npm stuff (besides audit.js there are only a few toys that I muck about with sometimes). I was not aware of the existence of the package-lock.json file.

It makes a heck of a lot of sense to use that instead of maintaining our own code to find dependencies. I will endeavour to update the code in the next couple of weeks. Thanks for the heads up!

**Comment by joh-klein** [comment]
I like the option of doing an audit without downloading all of the packages. Because it is (very likely) quicker. But I also feel safer not installing a potentially harmful package and only after it is already on my system discover that there are known issues with it.

**Comment by ken-duck** [comment]
Its been a while, but I am getting back down in there now and will attempt to have a solution out reasonably soon.

**Comment by ken-duck** [comment]
At long last, 3.1.0 has been published. You can now go

```
auditjs -p yarn.lock

auditjs -p package-lock.json
```
