### ISSUE TITLE
Erroneous CVE?

### ISSUE THREAD

**Issue by mmedemaskytap** [OSSIndex/auditjs#77]
auditjs is reporting that Node.js 8.15.1 has a vulnerability:

Found 1 CVEs

Severity: High [CVE-2018-1000168]  Improper Input Validation, NULL Pointer Dereference
 https://ossindex.sonatype.org/vuln/8a0c1adf-93c6-4986-96af-9b744b2eda07

https://nodejs.org/en/blog/vulnerability/june-2018-security-releases/

seems like `[8.4.0,8.15.1]` should be `[8.4.0,8.11.4]`

**Comment by scottbrady** [comment]
The Node.js blog post indicates that CVE-2018-1000168 impacts Node.js 8.4.x and higher and was fixed in 8.11.3.

https://nodejs.org/en/blog/vulnerability/june-2018-security-releases/

I would expect the vulnerability entry to contain `[8.4.0,8.11.2]`.

It looks like the NVD entry also contains an incorrect version range:

```
cpe:2.3:a:nodejs:node.js:*:*:*:*:*:*:*:*     Show Matching CPE(s) | From (including) 8.4.0 | Up to (including) 8.15.1
```

https://nvd.nist.gov/vuln/detail/CVE-2018-1000168

I'm guessing the ossindex entry grabbed the incorrect version range from NVD.

Is it possible to fix the version range on the ossindex side? Thanks!

**Comment by ken-duck** [comment]
The reasoning makes sense, and we can definitely override the data we get from NVD. I will endeavour to make the changes tonight. It will likely take a day or so for the changes to wend their way through our processing pipeline.

Thanks for letting us know!

**Comment by ken-duck** [comment]
This appears to be resolved: https://ossindex.sonatype.org/vuln/8a0c1adf-93c6-4986-96af-9b744b2eda07

**Comment by mmedemaskytap** [comment]
Thank you!!
