### ISSUE TITLE
Erroneous CVE?

### ISSUE THREAD

**Issue by mmedemaskytap** [OSSIndex/auditjs#78]
audit js is reporting a CVE for node 10.15.3

Severity: High [CVE-2019-5737]  Uncontrolled Resource Consumption ("Resource Exhaustion")
 https://ossindex.sonatype.org/vuln/39ead3ac-005f-4bd2-b912-563da75b526d

looks like this might be a false positive as it affects 'Up to (excluding) 10.15.2'

**Comment by ken-duck** [comment]
Hmm. This is curious. Looking at the OSSI data I see the version ranges look correct, and the REST API is returning correctly:

**Comment by mmedemaskytap** [comment]
Looks like it isn't being flagged anymore, thanks!

**Comment by ken-duck** [comment]
Odd. Glad it's working. Its possible that we found (or were notified) of the problem earlier and made a fix that rolled through just around the time you wrote. Thanks for letting us know!

**Comment by mcostelloskytap** [comment]
It appears CVE-2019-5737 (https://ossindex.sonatype.org/vuln/39ead3ac-005f-4bd2-b912-563da75b526d) is still being falsely reported for node 10.15.3 and 8.15.1 (and possibly others). This reappeared in our reports on Jun 24 after several days of not being flagged.

https://ossindex.sonatype.org/component/pkg:nuget/nodejs@10.15.3 https://ossindex.sonatype.org/component/pkg:nuget/nodejs@8.15.1

Can this issue be reopened for investigation?

**Comment by ken-duck** [comment]
Dang it. I am on it.

**Comment by ken-duck** [comment]
Or server is actually down at the moment (internal problems that we are working on). I wonder if this is some sort of strange reaction because of that; perhaps some old cached data being used?

I will dig some more.

**Comment by ken-duck** [comment]
We definitely had a data regression. I have re-processed some data and the valid results should find their way into the public database soon. I am going to do some poking around to see if I can figure out how it regressed.

**Comment by mcostelloskytap** [comment]
Thank you for the update and jumping on this so quickly!

**Comment by mcostelloskytap** [comment]
It looks like this was fixed for a while and then reappeared again around July 4.

**Comment by ken-duck** [comment]
Turns out our NVD feed was overriding my changes. I have done a fair rewrite/refactor of some of the importer and I expect this should not happen again. The versions should be repaired and published again tomorrow.

There is a side effect of this change, which is that CVEs which are updated in NVD will not necessarily update properly. I will be doing further updates to make it so we can retain our overrides without the feed overwriting our changes in the future.

This will remain open for at least a week while I watch to ensure that I really did catch the problem this time. Fingers crossed.

**Comment by mmedemaskytap** [comment]
Thank you! :D

**Comment by ken-duck** [comment]
It looks like this has properly been resolved. I am seeing good data still. Fingers crossed :|
